---
- hosts: digital_twin_vm
  become: yes
  vars_files:
    - /tmp/services.yml
  tasks:
    - name: Ensure services are installed and running
      package:
        name: "{{ item | regex_replace('(.service)$','') }}"
        state: present
      loop: "{{ services }}"
      ignore_errors: yes

    - name: Enable and start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"
      ignore_errors: yes
